service: tweet-scheduler

provider:
  name: aws
  stage: dev
  runtime: nodejs8.10
  memorySize: 128
  timeout: 3
  logRetentionInDays: 14
  environment:
    JWT_SECRET: ${self:custom.env.JWT_SECRET}
    CONSUMER_KEY: ${self:custom.env.CONSUMER_KEY}
    CONSUMER_SECRET: ${self:custom.env.CONSUMER_SECRET}
    TWEETS_TABLE: ${self:service}-${self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:Scan
      Resource:
        Fn::GetAtt:
          - TweetsTable
          - Arn

package:
  individually: true

functions:
  signIn:
    handler: src/functions/signIn.handler
    events:
      - http:
          method: POST
          path: /signIn
  authorize:
    handler: src/functions/authorize.handler
  getTweets:
    handler: src/functions/getTweets.handler
    events:
      - http:
          method: GET
          path: /tweets
          authorizer: authorize
  createTweet:
    handler: src/functions/createTweet.handler
    events:
      - http:
          method: POST
          path: /tweets
          authorizer: authorize
  updateTweet:
    handler: src/functions/updateTweet.handler
    events:
      - http:
          method: PUT
          path: /tweets/{tweetId}
          authorizer: authorize
  deleteTweet:
    handler: src/functions/deleteTweet.handler
    events:
      - http:
          method: DELETE
          path: /tweets/{tweetId}
          authorizer: authorize
  scrapeTweets:
    handler: src/functions/scrapeTweets.handler
    events:
      - schedule: rate(1 minute)
    memorySize: 512
    timeout: 60
  postTweets:
    handler: src/functions/postTweets.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - TweetQueue
              - Arn
    timeout: 60

resources:
  Resources:
    TweetsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment:TWEETS_TABLE}
        AttributeDefinitions:
          - AttributeName: tweetId
            AttributeType: S
          - AttributeName: tweetBody
            AttributeType: S
          - AttributeName: tweetTime
            AttributeType: N
          - AttributeName: userId
            AttributeType: S
          - AttributeName: accessToken
            AttributeType: S
          - AttributeName: accessTokenSecret
            AttributeType: S
        KeySchema:
          - AttributeName: tweetId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: userId-global-index
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
            Projection:
              ProjectionType: INCLUDE
              NonKeyAttributes:
                - tweetBody
                - tweetTime
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
          - IndexName: tweetTime-global-index
            KeySchema:
              - AttributeName: tweetTime
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    TweetQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:service}-${self:provider.stage}-queue
    LogBucket:
      Type: AWS::S3::Bucket
      BucketName: ${self:custom.config.logBucket}
      Properties:
        AccessControl: LogDeliveryWrite
        LifeCycleConfiguration:
          Rules:
            - Transitions:
                - StorageClass: STANDARD_IA
                  TransitionInDays: 30
  Outputs:
    LogBucketURL:
      Value:
        Fn::GetAtt:
          - LogBucket
          - DomainName

custom:
  env: ${file(./config/backend.yml):environment}
  config: ${file(./config/backend.yml):${self:provider.stage}}
  fullstack:
    bucketName: ${self:custom.config.siteBucket}
    distributionFolder: src/public
    clientCommand: browserify src/lib/client.js > src/public/client.js
    logging:
      bucket: LogBucketURL
  capacities:
    - table: TweetsTable
      index:
        - userId-global-index
        - tweetTime-global-index
      read:
        minimum: 1
        maximum: 5
        usage: 0.75
      write:
        minimum: 1
        maximum: 5
        usage: 0.75
  prune:
    automatic: true
    number: 3
  alerts:
    topics:
      alarm:
        topic: ${self:service}-${self:provider.stage}-alerts-alarm
        notifications:
          - protocol: email
            endpoint: ${self:custom.config.notificationEmail}

alerts:
  alarms:
    - functionErrors

plugins:
  - serverless-export-env
  - serverless-prune-plugin
  - serverless-plugin-optimize
  - serverless-plugin-aws-alerts
  - serverless-dynamodb-autoscaling
  - fullstack-serverless
  - serverless-offline
  - serverless-dynamodb-local
